package com.example.demo.Controller;

import com.example.demo.Model.UserInfo;
import com.example.demo.Model.UserInfoRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

@Controller
public class SignUp {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserInfoRepository userRepo;//Create user Object

    @RequestMapping(path="/addUser")
    public String creatUser(Model model) {
        UserInfo user = new UserInfo();
        model.addAttribute("user", user);

        return "new_user";
    }
    @RequestMapping(value = "/save", method = RequestMethod.POST)
    public String saveUser(@ModelAttribute("user") UserInfo user) {
        userRepo.save(user);

        return "redirect:/";
    }

}
